### ISSUE TITLE
Investigate JWST Data Analysis Tools

### ISSUE THREAD

**Issue by gkanarek** [spacetelescope/jwql#10]
Reproducing here from the Slack channel:

"During the NIRSpec team meeting on Tuesday, we had a demo of three of the tools the JWST Data Analysis Development Team have been working on - specviz, mosviz, and cubeviz. One of my team members asked whether JWQL would be able to use the tools for QL, but I said no, since they’re stand-alone tools and wouldn’t work in a browser. However, I did say that we might be able to learn from them in terms of choices they’ve made & issues they’ve faced when visualizing various JWST data products. we could also think about whether we want to try and be consistent with those tools in terms of theme/aesthetic/whatever."

So, once we move towards implementing the JWQL visualizations, we should make sure to investigate these tools, and see what we can adapt.

**Comment by SaOgaz** [comment]
I've been involved with the development for Specviz a bit, and know who to talk to about cubeviz, if anyone has questions in the future.

**Comment by bourque** [comment]
This really isn't on our radar anymore, and I don't see it being on our radar anytime soon.  I will close this for now, we can revisit sometime in the future if necessary.
