### ISSUE TITLE
Make filename parser more robust

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#1013]
Currently if the filename_parser comes across a file name that does not match any of its patterns, it raises an exception. This means that modules that call the filename parser, like the preview image generator, will crash if it comes across an unrecognized file. While we do need to be notified of unrecognized files, the code should handle this situation gracefully rather than crashing. This would save lot of time restarting jobs like the preview image generator.

**Comment by stscijgbot-jwql** [comment]
_This issue is tracked on JIRA as [JWQL-224](https://jira.stsci.edu/browse/JWQL-224)._

**Comment by stscijgbot-jwql** [comment]
_Comment by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert) on [JIRA](https://jira.stsci.edu/browse/JWQL-224?focusedCommentId=698784#comment-698784):_

This hasn't seemed to be an issue lately. But it probably would be best to handle unrecognized filenames better.

**Comment by stscijgbot-jwql** [comment]
_Comment by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert) on [JIRA](https://jira.stsci.edu/browse/JWQL-224?focusedCommentId=713827#comment-713827):_

#1614
