### ISSUE TITLE
Error displaying MIRI PID 1566

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#1027]
Looks like maybe a problem with text_scrape() ? Maybe there is no information coming back from text_scrape() ?

https://jwql-test.stsci.edu/MIRI/archive/1566/obs001/

@mfixstsci

**Comment by bhilbert4** [comment]
Hmm. Now I'm getting this same error on other programs. I wonder if this is actually a server issue.

**Comment by mfixstsci** [comment]
Interesting, I just tried to open the link above and the page loaded just fine. What're you seeing now @bhilbert4 ?

**Comment by bhilbert4** [comment]
It looks fine to me too. This may have been a symptom of the bug in my scaling algorithm that was using up all the memory on the server.
