### ISSUE TITLE
Sort Archive page by obs date

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#1110]
Add the ability to sort an instrument's Archive page by the date of the most recent observation. In this way, teams can reorder the programs such that programs that contain the most recent data are at the top.

**Comment by BradleySappington** [comment]
@bhilbert4 - I'm adding a "Recent" sort in addition to the "Ascending" and "Descending".  The proposal thumbnail will hold the most recent observation start time for sorting.
