### ISSUE TITLE
Failure of proposal search field on main page for 2593

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#1112]
When entering 2593 in the search box on the main page, the result that comes back is an error page that says "xxxx_pre-image.fits" does not follow jwst naming conventions.

Looks like this may be a new case that needs to be added to the filename parser.

**Comment by BradleySappington** [comment]
@bhilbert4 I spoke with @penaguerrero and Nirspec team doesn't want access to the pre-image.fits files.
