### ISSUE TITLE
Create a page showing all exposures flagged with a particular anomaly

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#1125]
From the NIRCam team meeting:

It would be helpful to have a page that shows the thumbnails/preview images for all exposures that have been flagged with a particular anomaly. 

We have this mostly done, from the Query The Archive button on the front page of JWQL. 
But:
1) We should probably change the button name to make it more clear what it does
2) At the moment, after selecting an instrument and anomaly and hitting Submit, the page fails to load.

**Comment by bhilbert4** [comment]
Page failure has this error:

KeyError
'anomalies'
jwql/website/apps/jwql/data_containers.py, line 1051, in get_thumbnails_all_instruments

get_thumbnails_all_instruments is given `parameters`, which is a dictionary that should contain the anomaly filter values selected by the user (e.g. 'nircam', 'f090w', 'diffraction_spike'). My investigation at the moment is showing that this dictionary is empty. And in fact, it's not a dictionary with a set of keys that all have empty values. len(parameters) returns zero, so there are no keys at all there.

**Comment by bhilbert4** [comment]
Further results:
In views.py: anomay_query_config seems to be properly populated in anomaly_query(), but is empty in query_submit()

**Comment by BradleySappington** [comment]
A global parameter is a dangerous way to handle the anomaly settings, different users may be attempting queries at the same time.  Going to look into changing into session data.
