### ISSUE TITLE
Add new anomaly types for NIRCam

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#1126]
Discussed in the NIRCam meeting today:

Should we add claws and wisps to the list of NIRCam anomalies? 
@bsunnquist is the best one to make the call on this.

We should also add a "scattered light" entry, to capture exposures with unexpected scattered light features.

**Comment by bsunnquist** [comment]
Yes, I think they should be added. The only issue is most claws are faint and require stacks of several exposures to see them - for these, I'll probably add some flagging option as part of my claw monitor page. But stronger claws will still show in single exposures, so I still think it's worth having it as an option.

Wisps will probably show in the majority of exposures on e.g. B4, but I still think it's worth tracking them as well, to help diagnose/model them.
