### ISSUE TITLE
Integrating FITSViewer with JWQL web app

### ISSUE THREAD

**Issue by gkanarek** [spacetelescope/jwql#114]
Continuing discussion with @laurenmarietta from #45.

So as it happens, the static files should be unnecessary - I just included them so I could do things like center the viewer on the page and control some other CSS stuff while using Bokeh server. We can hopefully use the Bokeh `embed` module instead - there's a user guide [here](https://bokeh.pydata.org/en/latest/docs/user_guide/embed.html) on how to do it. Other resources I've found are [here](https://www.hackerearth.com/practice/notes/bokeh-interactive-visualization-library-use-graph-with-django-template/) and [here](https://bokeh.github.io/blog/2018/6/13/release-0-13-0/) (specifically the part on custom templates). Are we using Jinja templating? If so, that might make things a little easier to embed.

An alternative is to run the FITSViewer off of Bokeh server, using the latter as a library, embedded in the larger framework of the Django app. There are some examples of that [here](http://bokeh.pydata.org/en/latest/docs/user_guide/server.html#embedding-bokeh-server-as-a-library), though not for Django.

I don't know enough about how Django works to know the best way to proceed here. Thoughts?

**Comment by bourque** [comment]
@bourque Reach out to individuals regarding support for Ginga

**Comment by bourque** [comment]
@gkanarek Have you heard of/used LSST's `firefly` tool?  Perhaps something we could possibly use?

https://firefly.lsst.io/index.html

**Comment by bhilbert4** [comment]
JWQL currently uses bokeh to interactively view fits images. While we could certainly do with some improved performance on this tool, that can be captured in a new issue. Closing this issue for now.
