### ISSUE TITLE
Return a list of viewed/new files

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#1154]
NIRSpec request:

Add the ability to create a list of new/viewed files for a given archive/proposal/observation.

@penaguerrero any other details on this? Is this something we should add to our API, so that it will give you a json list of files that can be downloaded? (Note that for our API you have to visit the link in a browser. We can't access API pages from a script due to the SSO layer between JWQL and the outside world.)

**Comment by penaguerrero** [comment]
thank you, I'm linking the previous  issue I had created about this https://github.com/spacetelescope/jwql/issues/1073

the summary is that we would like to be able to download a json or any file containing the following info:
Filename | EXP_TYPE | Filter | Grating | PATT_NUM | Viewed
JW01180027001_02101_00001_NRS1_CAL | NRS_MSATA | CLEAR | PRISM | 1 | yes
