### ISSUE TITLE
Make the query page fully functional

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#1178]
Update the query page such that users can filter and search for data using various observation/exposure properties. 

As part of this, move more information about exposures into the Django models, in order to make filtering easier.

- [x] #1184
- [x] #1185
- [x] #1186
- [x] #1187
- [x] #1188
- [x] #1189
- [x] #1190
- [x] #1191

**Comment by BradleySappington** [comment]
- [ ] Have Info in Thumbnails
- [ ] create datamodel entries to hold all jwql_query fields 
- [ ] update datamodels with query information from fits header
- [ ] update datamodels with query anomaly information from postgres DB
- [ ] verify all thumbnails are returned on query

**Comment by BradleySappington** [comment]
Here are the options for the filter keyword in the fits files. This list is a mix of the filters across all the instruments: https://github.com/spacetelescope/stdatamodels/blob/master/src/stdatamodels/jwst/datamodels/schemas/keyword_filter.schema.yaml

Here are the pupil values, which apply to NIRCam and NIRISS: https://github.com/spacetelescope/stdatamodels/blob/master/src/stdatamodels/jwst/datamodels/schemas/keyword_pupil.schema.yaml

Gratings, for NIRSpec: https://github.com/spacetelescope/stdatamodels/blob/master/src/stdatamodels/jwst/datamodels/schemas/keyword_grating.schema.yaml

**Comment by BradleySappington** [comment]
TODO list when merging all to main:

when merged into development and production the following will need to occur on the dev server, and the migrations should be merged to the production server:

$ python manage.py makemigrations
$ python manage.py migrate

We will need to temporarily disable the cronjobs on production for archive_database_update.py
Once halted we will need to run manually with the new update flag.

$ python archive_database_update.py update
this will take a few hours.
when complete enable cronjobs again

populate the anomalies in the models:
$python manage.py makemigrations
$python manage.py migrate
$python anomaly_db_transfer.py

**Comment by BradleySappington** [comment]
#1229 was needed to be in place before this work could continue
