### ISSUE TITLE
create datamodel entries to hold all jwql_query fields

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#1185]
datamodels must hold the following fields:
Filter
Aperature
Detector
Exp_Type
Read_Patt
Grating
Patt_Num
Anomalies
Subarray
Pupil
cat_type (add to proposal)

**Comment by melanieclarke** [comment]
@BradleySappington - can we please add exp_type to the RootFileInfo model as well?  There is a list of exptypes in Observation already, but I'm realizing that "observation" is a broader concept than I originally thought and it would be useful to have the specific exp_type for each root file as well.

**Comment by BradleySappington** [comment]
@melanieclarke, yeah good catch, its a list in the observation so wont do much good unless its held at the base level.

**Comment by BradleySappington** [comment]
when merged into development and production the following will need to occur on the dev server, and the migrations should be merged to the production server:

$ python manage.py makemigrations
$ python manage.py migrate
