### ISSUE TITLE
Encapsulate the filter/sort info so that separate tabs don’t interfere with each other 

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#1201]
Filter/sort information appears not to be session-specific. With two tabs open on different observations, the filter/sort information is shared between sessions, which breaks e.g. the Back button

**Comment by bhilbert4** [comment]
@BradleySappington do you know if this is still an issue?

**Comment by BradleySappington** [comment]
Confirmed still an issue

**Comment by bhilbert4** [comment]
This issue wasn't transferred to Jira by the bot for whatever reason. So we re-created the issue on JIRA. The mirrored github issue is #1572
