### ISSUE TITLE
Add more descriptive information to the image and exposure pages

### ISSUE THREAD

**Issue by melanieclarke** [spacetelescope/jwql#1304]
Currently, the image and exposure pages have very minimal descriptive information for the file(s) shown: only proposal, observation, visit, and detector (for image pages).

It would be helpful to include some more high-level description for context: the exposure type, proposal category, filter/grating, etc.  Essentially, any field that appears in filtering or sorting elsewhere in the application would be nice to have on the image pages.

**Comment by bhilbert4** [comment]
NIRSpec reports that this is high priority

**Comment by stscijgbot-jwql** [comment]
_This issue is tracked on JIRA as [JWQL-144](https://jira.stsci.edu/browse/JWQL-144)._
