### ISSUE TITLE
Use Ruff CI

### ISSUE THREAD

**Issue by stscijgbot-jwql** [spacetelescope/jwql#1314]
_Issue [JWQL-55](https://jira.stsci.edu/browse/JWQL-55) was created on JIRA by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert):_

Switch to using Ruff as the linter for new PRs. Previously we used pep8speaks as our linter, but this stopped working. From our research Ruff looks like the preferred way to go.

**Comment by bhilbert4** [comment]
We've moved away from this now that pep8speaks is working again.

**Comment by stscijgbot-jwql** [comment]
_Comment by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert) on [JIRA](https://jira.stsci.edu/browse/JWQL-55?focusedCommentId=698862#comment-698862):_

This work was put on hold when pep8speaks began working again. For now, we're happy with pep8speaks.
