### ISSUE TITLE
Build form to submit anomalies

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#142]
We will need a way for users to submit an anomaly that they visually identify in an image.  For WFC3, we did this with a set of checkboxes along side the observation (see below).  However, I am open to any better ideas.

Upon submitting an anomaly, a new record should be entered into our `Anomalies` table in our database (see #79).

<img width="889" alt="screen shot 2018-09-11 at 13 37 53" src="https://user-images.githubusercontent.com/2250769/45377213-f34f9b00-b5c7-11e8-936a-1d6fe925c474.png">

**Comment by hover2pi** [comment]
I'll take this ticket if no one else wants it.

**Comment by bourque** [comment]
@hover2pi Go for it!

**Comment by bourque** [comment]
@hover2pi Have you been able to connect and use the development database?  Is there anything I can do to help integrate this?  It would be nice to have this as part of our next release.
