### ISSUE TITLE
Add useful links to instrument-specific documentation on instrument landing pages

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#148]
Perhaps it would be convenient for our users if there were link(s) to JDocs and/or other useful instrument-specific information on each instrument landing page in the web application. Perhaps we could directly display any useful diagrams (e.g. detector layout) as well.

**Comment by catherine-martlin** [comment]
https://jwst-docs.stsci.edu/display/HOM/JWST+User+Documentation+Home
