### ISSUE TITLE
Scroll bar for navigating through preview images with many integrations

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#149]
Currently our webpage for displaying a preview image displays one integration at a time with the option to click a right or left arrow button to display the next or previous integration.  It would perhaps be more useful to turn this feature into some sort of scroll bar instead of having to click a button many times.

**Comment by bhilbert4** [comment]
Also keep in mind that in some cases (time-series observations) there will be cases with hundreds or thousands of integrations per exposure. We may want to come up with a smart way to deal with this. The majority of observations will most likely have only a couple integrations per exposure.
