### ISSUE TITLE
Add documentation tab to web app

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#153]
We now have publicly-facing documentation on ReadtheDocs: https://jwql.readthedocs.io/en/latest/

We could add a `Docs` tab in the main navbar of the webapp to point to this.  Perhaps also a pointer to it in the About page.

**Comment by bourque** [comment]
@bhilbert4 This is a pretty simple issue and would be a good first introduction to contributing something to the web app, want to try it?

**Comment by bhilbert4** [comment]
Sure!
