### ISSUE TITLE
Indicate an anomaly is marked in some detectors 

### ISSUE THREAD

**Issue by stscijgbot-jwql** [spacetelescope/jwql#1557]
_Issue [JWQL-193](https://jira.stsci.edu/browse/JWQL-193) was created on JIRA by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert):_

Currently, when flagging an anomaly at the detector level (i.e. flag a Short in NRS1), the checkbox for that anomaly is checked on the detector page. However, when you look at the group page for that exposure (where you see all the detectors), the anomaly box is not checked. This is because the anomaly box on the group page is not checked unless all detectors in that group have that anomaly flagged.

However, this means that when browsing through data, if you are browsing at the group level, you will miss any flagged anomalies. 

Is there a way to indicate on the group page that a particular anomaly is present in one/some of the detectors in that group? Perhaps some third option besides having the box be unchecked or checked? e.g. if there is a dot in the center of the checkbox, then the anomaly is present in some of the detectors?

**Comment by BradleySappington** [comment]
handled with https://github.com/spacetelescope/jwql/pull/1564
