### ISSUE TITLE
App crashes when fits file is not present

### ISSUE THREAD

**Issue by stscijgbot-jwql** [spacetelescope/jwql#1558]
_Issue [JWQL-192](https://jira.stsci.edu/browse/JWQL-192) was created on JIRA by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert):_

Currently <https://jwql.stsci.edu/nircam/exposure/jw03990237001_06201_00003/> crashes with the error:

 
# FileNotFoundError at /nircam/exposure/jw03990237001_06201_00003/
jw03990237001_06201_00003_nrcblong_rate.fits is not in the predicted location: jw03990/jw03990237001/jw03990237001_06201_00003_nrcblong_rate.fits

in utils/utils.py line 655.

(called from filesystem_path() which was called from get_additional_exposure_info() which was called from view_exposure().)

There is a thumbnail image for this exposure, as seen on the Observation level page. At that point, it might be better to have the exposure-level page load, but show a figure that informs the user that the requested file is not present in MAST? I haven't checked, but I have a feeling that the uncal file is present, and it's just that the pipeline hasn't completed yet, and so the rate image is not yet present in MAST.

**Comment by BradleySappington** [comment]
fixed with #1549

**Comment by stscijgbot-jwql** [comment]
_Comment by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert) on [JIRA](https://jira.stsci.edu/browse/JWQL-192?focusedCommentId=713935#comment-713935):_

handled with #1549
