### ISSUE TITLE
Python 3.6 Requirement

### ISSUE THREAD

**Issue by alexyermolaev** [spacetelescope/jwql#157]
Please add Python 3.6 requirement to the dependencies in environment.yml  i.e.

`dependencies:
  - python=3.6`

**Comment by jason-neal** [comment]
` - python=3.6.4`  is already a dependency in `environment.yml`.

Are you suggesting it be changed to just ` - python=3.6`

**Comment by bourque** [comment]
@jason-neal You're right, `python=3.6.4` is already in there.  I think this is a non-issue afterall.
