### ISSUE TITLE
Ensure web application is accessible!

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/jwql#161]
Some tips for making web applications as accessible as possible, for differently-sighted users (and also just making apps better in general):
* Using HTML
    * Provide alt tags for images
    * Pay attention to the tabindex
    * Headers (h1-h6): actually use them! Organize documents like trees, and don’t skip levels. 
    * Mark things as headers, articles, figures, footers. (Look here: https://www.w3schools.com/tags/)
* Using ARIA to actually define the roles of different tags (e.g. role=“button”): https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA

Web content disability guidelines: https://www.w3.org/TR/WCAG21/

**Comment by laurenmarietta** [comment]
ST also has a page with a LOT of resources on web app accessibility: https://innerspace.stsci.edu/pages/viewpage.action?spaceKey=OPO&title=Accessibility

**Comment by bourque** [comment]
Thats cool that this exists!

**Comment by bourque** [comment]
Per @catherine-martlin suggestion, maybe we can tackle this in a few hours long hack session in a conference room!
