### ISSUE TITLE
Find alternative to Donut chart for monitor_mast

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#177]
With the upgrade to `bokeh=1.0` (#155, #176), the `bokeh.charts` library, which contains `Donut` has been deprecated.  We need to find a different way to plot the data gathered by `monitor_mast`.

At a quick glance of `holoviews`, there doesn't seem to be a clear alternative to `Donut`. 

Perhaps we could just make `bokeh` pie charts instead? (e.g. https://bokeh.pydata.org/en/latest/docs/gallery/pie_chart.html)

**Comment by bourque** [comment]
@hover2pi Since you are the owner of this code, would you mind digging into this one?

**Comment by hover2pi** [comment]
Fixed in PR #188 .
