### ISSUE TITLE
Add project description and higher level documentation to ReadTheDocs

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#180]
We have a working ReadTheDocs page with API documentation here: https://jwql.readthedocs.io/en/latest/

It would be nice to add some higher-level documentation to go along with this, such as a project description and how to install/use the `jwql` package.

**Comment by laurenmarietta** [comment]
Scrolling through the ReadTheDocs, it also seems like we could use another level of headings within the different sub-packages? For instance, under the "utils" tab, the docs for `utils.logging_functions`, `utils.permissions`, etc. all run together. I imagine we would prefer to have headings for those modules  
 (`logging_functions`, `permissions`, ...) within the sub-package docs to delineate between them.

**Comment by bourque** [comment]
@laurenmarietta Good point, agreed!
