### ISSUE TITLE
Write checklists for contributing

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/jwql#183]
It would be helpful to curate checklists for contributors to use – both for developers that are writing new code for the project, and for reviewers that are reading over that code. These can remind people to include things like sphinx-formattable docstrings, any necessary new tests, PEP8 standards, and more.

(This idea comes from a really great talk at DjangoCon, "Code Review Skills for Pythonistas" by Nina Zakharenko: https://www.youtube.com/watch?v=ZsT7nSRQ8S4)

**Comment by bourque** [comment]
I have created a draft checklist here: https://github.com/spacetelescope/jwql/wiki/Checklist-for-Contributors-and-Reviewers-of-Pull-Requests

@laurenmarietta Since this is a wiki page I can open a proper pull request to review this.  Could you take a look and let me know what you think?  Am I missing anything or should anything be changed?

**Comment by laurenmarietta** [comment]
How obnoxious that you can't submit a PR for wiki pages! I'll just paste the changes I think would be appropriate in this comment.

I think this checklist is great and covers basically everything. I only thought of a couple more things to add after reviewing the [code review slides](https://speakerdeck.com/nnja/code-review-skills-for-pythonistas-djangocon-2018) (hopefully the list isn't too long now). My main comment is that I think it could benefit from a bit more specificity on the contributor side. Here's what I mean - let me know what you think.

---

## Checklist for Contributors

#### Pertaining to the code:
- Does the code conform to the [`pyql` Style Guide](https://github.com/spacetelescope/jwql/blob/master/style_guide/style_guide.md)?
    - Use a linter like `pylint` to check for proper formatting.
- Is any of the code functionality already available via native or third-party python libraries?
- Does the code execute successfully?
    - Check that the existing test suite passes.
    - Check that any newly added functionality runs without errors.
    - If modifying the web application, check that all pages and buttons work as expected.
- Is the code documented and commented sufficiently such that it is easy to read and follow?
    - Include docstrings for all new modules, classes, and functions.
- Have all debugging print statements been removed?
- Does the code make use of the `logging` module to document its processes?
- Does the code contain sufficient exception handling?
- Does the code contain no deprecation warnings?
- Does the code include all necessary additions/changes to jwql.readthedocs.io (via `docs/source/*.rst` files)? See the [wiki](https://github.com/spacetelescope/jwql/wiki/Adding-Sphinx-API-Documentation) for instructions.
- Does the code include all necessary new dependencies or dependency updates?
    - Update `requirements.txt`
    - Update `environment.yml`
    - Update `setup.py`
- Does the code include all necessary unit tests?
    - Generate a coverage report with `pytest` to verify that new code is covered by tests. _(It might be necessary to include some sort of brief explanation for how to do this?)_

#### Pertaining to the pull request:

- Is the PR limited to 400 lines of code? If not, consider breaking it up into multiple PRs.
- Does the PR have a concise and descriptive title?
- Does the PR link to and close the relevant issue?
   - Pro tip: Including "Closes #n" in a PR will automatically close that issue when the PR is merged.
- Does the PR have a sufficient description as to make it clear what the reasons for the changes are?
- Is the PR merging into `upstream/master` from `user/branchname`?
- Are you listed as an assignee to the PR?
- Does the PR have proper labels?

**Comment by bourque** [comment]
@laurenmarietta These are great additions!  Thank you.  I just have a few lingering thoughts/questions/additions:

1. I think we should add another bullet here:

> - Is the code documented and commented sufficiently such that it is easy to read and follow?
>    - Include docstrings for all new modules, classes, and functions.
>    - Include in-line comments to provide necessary context

2. I agree with your comment here, we can add that when we figure out #134 (@SaOgaz) 

> - Does the code include all necessary unit tests?
>    - Generate a coverage report with pytest to verify that new code is covered by tests. (It might be necessary to include some sort of brief explanation for how to do this?)

3. For this one, I'm not sure that we should use an explicit number here.  I think there still exists cases where it makes sense to have a 400+ line pull request.  For instance, if the PR adds a 400+ line monitor, I think it makes sense to keep all of the context together within one PR.  Perhaps we could say something like "Is the PR excessively long and/or covers multiple issues?  If so, consider breaking it up into multiple PRs."

> - Is the PR limited to 400 lines of code? If not, consider breaking it up into multiple PRs.

**Comment by laurenmarietta** [comment]
Finally getting a chance to respond to your thoughts!

1. I agree 100%!
2. As I've been developing the MAGIC, which doesn't have any automated coverage report generators set up, I've been using an inline `pytest` command that generates a local HTML coverage report. I believe the command is something like this:
`pytest ./tests/test_psfgrid.py --self-contained-html --cov=./ --cov-report=html`
and it requires having `pytest-cov` and `pytest-html`. Users can get coverage reports this way without having codecov or coveralls set up. Not sure if it would be worth the work/effort to explain all that, though, if there is hope #134 being completed soon-ish?
3. I also agree completely; better to use discretion there.

**Comment by bourque** [comment]
@laurenmarietta This `pytest` coverage stuff is neat!  And seems like a really good alternative until we get #134 up and running.  

I suggest that we open a PR to add `pytest-cov` and `pytest-html` to the `jwql` environment, and then in the checklist we can say:

> - Does the code include all necessary unit tests?
>     - To see where unit tests may be lacking, generate a coverage report with `pytest` to verify that new code is covered by tests:
>    ``pytest ./jwql/tests/ --self-contained-html --cov=./ --cov-report=html``
>    The coverage report can be viewed by opening `jwql/tests/htmlcov/index.html` in a browser.

Whenever we get #134 going we can easily change this text to mention `codecov` or `coveralls`
