### ISSUE TITLE
Write test for basic astroquery.mast query

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#186]
Currently our Jenkins builds are failing (e.g. https://ssbjenkins.stsci.edu/blue/organizations/jenkins/STScI%2Fjwql/detail/PR-185/2/pipeline) for what seems like an issue with `monitor_mast.py` but the problem is actually that the query to the archive via `astroquery.mast` is returning no results.

Regardless of whatever the exact issue with that is, this gave me the idea that we should have a unit test that performs a simple query using `astroquery.mast` just to see if that service is returning results as expected.  This way, it will be more apparent that it is `astroquery.mast` that is the source of any issues.

**Comment by hover2pi** [comment]
Addressed in #227
