### ISSUE TITLE
Establish logging guidelines

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#189]
Per @bhilbert4 's idea, we should establish some guidelines for how to properly log the execution of a script so that we can build tools that can interact with the logs in a standardized way.  We can document these guidelines in a wiki page perhaps.  This would also help solve some of the ideas in #135. 

Adding a checklist for this: 

- [x] Flush out logging functions regarding monitoring our monitors - see #135 
- [x] Create the `/style_guide/logging_guidelines.md` page
- [x] Update the `/style_guide/example.py` / the notebook
- [x] Update `/style_guide/style_guide.md` as well as the Wiki to include proper links and logging guideline references

**Comment by catherine-martlin** [comment]
Would it be better to add a section to an existing Wiki such as [Style Guide](https://github.com/spacetelescope/jwql/wiki/Style-Guide) or the original [logging page](https://github.com/spacetelescope/jwql/wiki/JWQL-Logging-Function:-The-Why's-and-The-How)? 

I'm considering an addition to the logging page with a link from the style guide to remind people.

**Comment by catherine-martlin** [comment]
A small update was placed [here](https://github.com/spacetelescope/jwql/wiki/Style-Guide) regarding the soon to come `jwql`-specific logging standards.

**Comment by catherine-martlin** [comment]
This will be addressed by PR #258

**Comment by bourque** [comment]
See #258
