### ISSUE TITLE
Build web app view for displaying monitor log files

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#216]
We should build a view that allows a user to view all available log files for each monitor, as well as view the contents of a selected log file.

See the attached screen shot of how this looks on WFC3 Quicklook

<img width="1440" alt="screen shot 2018-12-13 at 23 23 27" src="https://user-images.githubusercontent.com/2250769/49983035-2b9ba800-ff2e-11e8-8c2d-084bcec1a6f3.png">

**Comment by catherine-martlin** [comment]
@bourque I'd be happy to take this on - it'd be good to add in some more app/coding to my workload.

**Comment by bourque** [comment]
@catherine-martlin Are you still interested in doing this?  And if so, do you think you'd be able to complete this for our next sprint?

**Comment by catherine-martlin** [comment]
@bourque - Yep! I can fit that in for our next sprint!

**Comment by catherine-martlin** [comment]
See PR #384 for current progress
