### ISSUE TITLE
Write tests for web app

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/jwql#220]
As mentioned in #208, it is increasingly important to develop tests for the increasingly complex web app!

Django actually has its [own tools for writing web app tests](https://docs.djangoproject.com/en/2.1/topics/testing/overview/) that seem to be very helpful for sending test requests and responses and such. 

And as a bonus, it looks like there is a [`pytest` plugin](https://pytest-django.readthedocs.io/en/latest/) that would let our web app tests be run with our usual `pytest` call rather than having to include a secondary Django test call. (Though hopefully a separate call wouldn't be too difficult to include into our Jenkins test case.)

**Comment by bourque** [comment]
@laurenmarietta I am going to assign myself to this one as well -- I probably can muster up some time to help with this.

**Comment by bourque** [comment]
Another thing to consider -- perhaps it is better to use [`pytest-django`](https://pytest-django.readthedocs.io/en/latest/index.html), which is a plugin for `pytest` for testing Django applications

**Comment by bhilbert4** [comment]
Closing in favor of #969
