### ISSUE TITLE
Write utils function that returns the full path to a given file in the filesystem

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#230]
It would be convenient to have a function that, given a filename (e.g. `jw86600006001_02101_00008_guider1_cal.fits`), returns the full path to that file in the filesystem (e.g. `/the/jwql/filesystem/86600/jw86600006001_02101_00008_guider1_cal.fits`).  This will probably be a commonly used functionality, so it would be nice to be able to just call `utils.get_full_path(filename)` or something.

**Comment by bhilbert4** [comment]
Do we want this to raise an error if the file is not in the constructed directory? Or just return the full path and let the user perform checks?

**Comment by bourque** [comment]
@bhilbert4 I'm in favor of raising an error, I don't think it hurts.  The user can always write a `try/except` around that error if need be, and it will potentially save the user from having to write a `if os.path.exists()` condition.

**Comment by bourque** [comment]
Completed via #229
