### ISSUE TITLE
Add constants.py

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/jwql#234]
There is a pretty large collection of constants, lists, and strings currently at the beginning of `utils/utils.py` - and I am sure that collection will only get bigger as we keep developing. It might be helpful (or at least cleaner) to organize all the relevant JWQL constants in a `constants.py` module that lives either in the main `jwql` directory, or else in `jwql/utils`.

(I got this idea from @Johannes-Sahlmann in the MIRaGe project: https://github.com/spacetelescope/mirage/blob/master/mirage/constants.py)

**Comment by bourque** [comment]
Completed via #253
