### ISSUE TITLE
Links to external webpages should open in new tab

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#236]
I think it would be a good idea to make any links to external webpages (e.g. `Documentation` link on homepage, instrument-specific links to JDocs, etc.) open in new tabs instead of redirecting away from the `jwql` web app.  That way, our web app will stay open in the user's browser and they can rest assured knowing that our wonderful application is still at their fingertips.

**Comment by cracraft** [comment]
Pull request submitted with requested changes.

**Comment by bourque** [comment]
See #306
