### ISSUE TITLE
Ask IT for production database

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#257]
We could use a test `postgresql` database that we can use as a sandbox for development purposes.  This would help the likes of @hover2pi with #142 and @SaOgaz and @cracraft with #86.

**Comment by SaOgaz** [comment]
From what I can gather talking to IT about the reset problem, we should make our current DB the test one, and ask for a permanent production DB.

**Comment by bourque** [comment]
@SaOgaz Good point.  In that case we can ask IT to set us up with a database on one of our production servers and then use the one on the dev server as a sandbox

**Comment by bourque** [comment]
I have requested a production database from IT!

**Comment by bourque** [comment]
We now have a production database! I will put instructions in the home directory of the production VMs with instructions on how to access.
