### ISSUE TITLE
Smart search for program numbers (without zeros)

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/jwql#260]
As @Johannes-Sahlmann mentioned in #253, it would be preferable if the JWQL search feature didn't enforce trailing zeros. That is, to search for data from program 778, you shouldn't have to type 00778 into the search.

Should be an easy fix, but will require parsing what are currently strings into ints.

**Comment by bourque** [comment]
Perhaps a separate issue, but we should also be sure to enable a user to enter a non-zero-padded URL (e.g. `https://dljwql.stsci.edu/FGS/archive/315/` instead of ``https://dljwql.stsci.edu/FGS/archive/00315/``) and have everything work.
