### ISSUE TITLE
Consider adding new OSes to Jenkins

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/jwql#271]
Currently, our test suite is just being run for Linux. We should consider adding more builds that test different operating systems - and maybe even versions of Python!

**Comment by obviousrebel** [comment]
What specific Oses and python versions should we test against?

**Comment by bourque** [comment]
@obviousrebel I am thinking that we should at least be testing both Linux and OS X, for python 3.5 and 3.6.

**Comment by laurenmarietta** [comment]
Just noting that we never tackled the idea of different _operating systems_. Currently Jenkins is only testing for Linux.

**Comment by bourque** [comment]
I thought I saw a comment somewhere that mentioned that there may not exist a OS X server for Jenkins at the institute (yet), so that might be a roadblock here.  @obviousrebel Do you know if it would be possible to have an OS X Jenkins build at this point in time?

**Comment by obviousrebel** [comment]
@bourque 

Thats correct, I mentioned it here: https://github.com/spacetelescope/jwql/pull/387#issue-273600426

SSB jenkins doesn't currently have any OSX nodes. Once one was added, the only change in the Jenkins file would be to add "osx" to the matrix_os:
```
matrix_os = ["linux-stable", "osx"]
```

@rendinam I know I asked before, but would this be  possible?

**Comment by rendinam** [comment]
We have inquired about adding macos nodes to the proper network segment to allow Jenkins to use them, but the request was not met with much enthusiasm. It's been a while though, so I can look into it again.

**Comment by bourque** [comment]
Thank you all for looking into that!

**Comment by rendinam** [comment]
Due to security stipulations from ITSD, it looks like hosting our own macos builds via Jenkins will not be possible. We will have to explore other options. I have heard that Azure pipelines (https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/what-is-azure-pipelines?view=azure-devops) is reasonably easy to set up and supports builds on multiple OSs, including macos. If you would like to explore using that, let me know and I can enable the service on this repository.

**Comment by laurenmarietta** [comment]
For the record, I (think!) have also figured out how to get Mac OSX builds working with Travis, on MIRaGe.

However I'm not sure how either of those options would affect our ultimate goal to allow our CI builds access to central storage, @bourque ...
