### ISSUE TITLE
Add a specific error when user is missing a config file?

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/jwql#274]
As @DanielKuebi was setting up the JWQL package, he found that he didn't have the `config.json` file that is required to run the package.

I looked back into `utils.py`, and I'm thinking it might be wise to raise a specific error when a user doesn't have the `config.json` file, so it is clear when that is the problem. Maybe even the error message could encourage them to email `jwql@stsci.edu` to ask a team member for assistance? 

If anyone thinks this isn't a good idea for security reasons, please say so.

**Comment by bourque** [comment]
@laurenmarietta I think this is a great idea.  I was also thinking that maybe we should make it more clear in the installation instructions in `README` that the user must have this file.
