### ISSUE TITLE
Instrument logos not showing on web app homepage

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#286]
For some reason the static images for the instrument logos no longer appear on the homepage.  This is particularly odd since the other static files seem to render fine throughout the rest of the web app.

**Comment by bourque** [comment]
This is happening for me locally too, so whatever the issue is, it must be independent of the dev server.

**Comment by laurenmarietta** [comment]
That's odd - it's not happening for me locally on `master`...
