### ISSUE TITLE
JWQL web app home page example query error

### ISSUE THREAD

**Issue by Johannes-Sahlmann** [spacetelescope/jwql#308]
When submitting the example program number `86600` in the search field of the web app home page, an error is raised: 
<img width="1317" alt="screen shot 2019-02-27 at 15 48 59" src="https://user-images.githubusercontent.com/13909167/53521881-3d113c80-3aa7-11e9-9dc0-9269bb94c10e.png">

**Comment by bourque** [comment]
Thanks for opening an issue @Johannes-Sahlmann.  I suspect this has to do with the recent switch to an updated filesystem that I recently made (#292), and likely this will introduce some issues in various places.

**Comment by bourque** [comment]
FYI, I switched the path to the `filesystem` back to what it was before #292.  Until we can figure out some of the issues associated with the updated filesystem, I will leave it there to avoid errors with the web app.

**Comment by bourque** [comment]
Now that #315 is merged, the original error that @Johannes-Sahlmann appears to be solved, however there is a new error:

<img width="973" alt="screen shot 2019-03-04 at 16 15 48" src="https://user-images.githubusercontent.com/2250769/53763456-e33eb700-3e98-11e9-9fbf-564926f1d42c.png">

**Comment by laurenmarietta** [comment]
Weird stuff. I'll take a look!
