### ISSUE TITLE
Determine what to do with non-compliant filenames

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#311]
With the updated filesystem (#292), I ran `test_utils.test_filename_parser_whole_filesystem` and it kicked back 1578 files that could not be parsed, some common examples include:

```
jw00799003001_gs-acq1_2019154181705_stream.fits
jw00799003001_gs-fg_2019154183426_cal.fits
jw10005-c1001_t001_nircam_f430m-maskrnd-sub320a430r_psfstack.fits
jw10005003001_02102_00001_nrcalong_c1001_psfalign.fits
jw90001001002_02101_00001_nis_o001_crf.fits
jw00729011001_gs-id_1_image_cal.fits
jw00729011001_gs-id_1_stacked_cal.fits
```

We should reach out to DMS folks and see what the dealio is with these types of files.

**Comment by Johannes-Sahlmann** [comment]
*_gs_acq1_* are FGS guide star acquisition data
*_gs_fg_* are FGS fine guide data
*_gs_id_* are FGS identification step data

**Comment by bourque** [comment]
@Johannes-Sahlmann Do you happen to know if those files are indeed in the proper naming convention and will permanently exist in the JWST archive?

**Comment by Johannes-Sahlmann** [comment]
I am confident that they will exist permanently in the archive.
I do not know whether these examples are properly named.

**Comment by bourque** [comment]
Ok, thanks!

**Comment by laurenmarietta** [comment]
@shanosborne and I came across some FGS files like this in the filesystem the other day (the `gs-id`, `gs-acq`, and `gs-fg` files). They are products of the GUIDER pipeline and, like Johannes said, we should definitely expect to see files like this in the archive. 

I can ping some FGS people to see if I can determine what the naming structure for them will be.

I'm also happy to ask about the other filetypes, @bourque, if you haven't already?

**Comment by bourque** [comment]
@laurenmarietta Sounds good, go for it!
