### ISSUE TITLE
Build function to hide exclusive access content in web app

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#312]
Before we build an external facing production web server (#294), we should build in a convenient and secure way to hide content within the web app if the user is not authenticated.

**Comment by laurenmarietta** [comment]
When you say "content", I take it you mean specific material on a page rather than a whole page? FYI, maybe someone could see the EDB page but then not be able to submit a query, or something similar?

**Comment by bourque** [comment]
@laurenmarietta Yeah, that is mainly what I meant, but you raise a good point.  There may be cases where we want to hide an entire page, so we will also have to address that functionality.  Perhaps we could do something like "if user isnt authenticated, redirect to a "not authorized" page".

**Comment by bourque** [comment]
I am finding that there needs not exist a separate function for this, but rather just some conditions within `views.py` and/or specific HTML templates in the places where we want to hide the content.
