### ISSUE TITLE
Build diagram showing JWQL technologies and components

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#325]
It would be nice to have a general diagram that shows the overall technological landscape of the `jwql` project and how the various technologies/components relate to each other.

**Comment by bourque** [comment]
Here is a rough draft:

![screen shot 2019-03-05 at 14 55 30](https://user-images.githubusercontent.com/2250769/53833575-dbdde300-3f56-11e9-95ec-98d3558fc47d.png)

@spacetelescope/jwql Any thoughts on how I might make this look better?  Can you think of anything I am missing? 

Attached is the file in case anyone would like to make edits. 
[jwql_technologies.pptx](https://github.com/spacetelescope/jwql/files/2932594/jwql_technologies.pptx)

**Comment by laurenmarietta** [comment]
This is exactly the kind of procrastination I was looking for today 😈 

I think this might be too busy, but here's another option (including a new "project management" section and moving things around a bit):
<img width="786" alt="screen shot 2019-03-05 at 5 05 23 pm" src="https://user-images.githubusercontent.com/12650803/53840783-05076f00-3f69-11e9-9536-217fd54b9130.png">

Apparently you can't attach a keynote file (easier to make logos transparent than in PPT) to GitHub, but I'm happy to Slack it to anyone who wants it.

**Comment by bourque** [comment]
Thanks @laurenmarietta, this is awesome!! Good call on including Jenkins, I totally forgot about that.  

I wonder if it would be better to change "Software Management" to "Software Tools" instead, and add logos for `pytest` and `bokeh`.  And then in "Project Management" add logos for `Anaconda` and `ReadTheDocs`.  What do you think?

I'd be happy to play around with it if you want to send me the file.

**Comment by bourque** [comment]
Here is a slightly updated version:

<img width="842" alt="screen shot 2019-03-06 at 12 05 32" src="https://user-images.githubusercontent.com/2250769/53905250-0f337700-4016-11e9-9252-ec214eb0835e.png">

**Comment by bourque** [comment]
I will close this issue for now.  We can make tweaks to this as we see fit.
