### ISSUE TITLE
Determine way to mark specific tests to only run on private Jenkins server

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#344]
Now that we have a private Jenkins server that can access our `config.json` file on central storage (#203), we can now run the handful of tests that require that file.  However, we need to find a way to mark those test to only be triggered if the server is the private Jenkins server, and not the public one.

@SaOgaz suggests there is a way to do this in `pytest`, or perhaps we could build our own decorator.

**Comment by SaOgaz** [comment]
You could even use pytest skip
