### ISSUE TITLE
Update edb_mnemonic_query notebook

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/jwql#362]
I've been trouble-shooting some problems with my MAST token (ends up that it expired 🤷‍♀️), and I looked to @Johannes-Sahlmann's notebook on EDB queries. I realized that notebook is out of date, with respect to both package structure and the MAST authentication protocol.

It would be nice to keep that notebook updated - though maybe it should actually now live at https://github.com/spacetelescope/jwst-dms-edb/tree/master/jwedb rather than here?

If we do move the notebook out of the repo, it might be smart to add a wiki page for how to set up authentication with MAST. Especially since, as far as I know, the only place with instructions for how to do so are currently written down is in that notebook? (Let me know if I am incorrect there.)

**Comment by Johannes-Sahlmann** [comment]
I think we should keep this notebook here in jwql.
