### ISSUE TITLE
Specify Dark Monitor Plots

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#369]
I thought there was already an issue open for this, but I couldn't find it. I just wanted to write down a list of dark monitor-related plots to be displayed in the web app.

1. Histograms of dark current rates. Currently there are separate histograms generated for each amplifier, as well as for the full detector, for all instruments. This should change a bit, as MIRI's readout pattern interleaves all the amplifiers. The code as-is won't be able to handle that. 
2. Mean dark current versus time (across multiple dark monitor runs)
3. Hot/dead/noisy pixels: Maybe display the mean dark rate image and mark the locations of any new hot/dead/noisy pixels with different colored dots? If nothing new, still display the mean dark rate image as that can still be useful.
4. Display tables of new hot/dead/noisy pixels? How will potential users get this information, assuming they won't have access to the JWQL database? Add to API?

Bonus: 
I think it would be interesting and useful to be able to plot the mean dark rate versus certain EDB mnemonics. For NIRCam we would want to watch dark rate versus the ASIC voltage and the FPA temperature.

In the case where the mean dark rate differs from the historical mean by some amount, overplot current and historical histograms?

**Comment by bourque** [comment]
I am going to label this as high priority, as it would be really nice to have working plots for our upcoming TIPS talk.  Once we get #222 integrated (which @gkanarek seems to be close to finishing), it should be rather easy to use @gkanarek's `bokeh` templating software to build these plots.
