### ISSUE TITLE
EDB query times incorrect?

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/jwql#392]
I've been interacting a lot with the EDB web page today, and I keep seeing some weird behavior where it looks like the EDB query results plot is completely ignoring the start and end date/time.

In the screenshot I'm including here, I restrict the search to one day in August 2017, but the plot is clearly showing data points from 2019:
<img width="999" alt="Screen Shot 2019-04-26 at 4 32 56 PM" src="https://user-images.githubusercontent.com/12650803/56835054-22f2a100-6841-11e9-8691-f92d041529f2.png">
@Johannes-Sahlmann have you seen this before?

**Comment by Johannes-Sahlmann** [comment]
No I have not seen this before, but it may be a corner case of the MAST service that we use. 
As a double check, can you reproduce this situation with a programmatic query (not via the web app)?

I could look into this as part of the EDB wrapup in the current sprint.

**Comment by laurenmarietta** [comment]
The questionable time problem does unfortunately seem to be occurring in the programmatic query as well. Including here a screenshot of trying to query two days in September 2017 and getting back two entries: one from February 2017 and another from August 2018:

<img width="827" alt="Screen Shot 2019-04-29 at 3 28 04 PM" src="https://user-images.githubusercontent.com/12650803/56921363-9ab80a00-6a93-11e9-95e9-ba6e25850193.png">

**Comment by Johannes-Sahlmann** [comment]
I can reproduce this behaviour (approximately) using the web portal (https://mast.stsci.edu/portal/Mashup/Clients/JwstEdb/JwstEdb.html) so this is likely not an issue of `jwql` itself.
Strangely, the web portal query returns three entries (see attachment) whereas the programmatic queries using jwql return two entries. I will forward this to MAST. 

<img width="1426" alt="Screen Shot 2019-05-08 at 13 40 47" src="https://user-images.githubusercontent.com/13909167/57396262-09821b00-7198-11e9-842c-6258be50f5c7.png">


[IGDP_MIR_IC_DET_TEMP-20170214T230000-20180808T184434.txt](https://github.com/spacetelescope/jwql/files/3158680/IGDP_MIR_IC_DET_TEMP-20170214T230000-20180808T184434.txt)

**Comment by Johannes-Sahlmann** [comment]
According to MAST staff, this is the expected behaviour: 
"The EDB returns from the datapoint that precedes the requested start time to the datapoint that follows the requested end time, thus ensuring a containment. "

We should possibly include a note on this in the documentation of jwql and/or jwedb

**Comment by Johannes-Sahlmann** [comment]
I added some notes on this in the relevant docstrings, see #402

**Comment by laurenmarietta** [comment]
Thank you for figuring this out, @Johannes-Sahlmann!
I wonder whether the EDB plotting feature on the web app should be altered, now, so that only the points in the requested timeframe (if there are any) are shown. Probably a discussion for a separate issue.
