### ISSUE TITLE
Jenkins build failing 

### ISSUE THREAD

**Issue by Johannes-Sahlmann** [spacetelescope/jwql#403]
The build of #402 is failing which seems to be unrelated to the changes it introduces.
`CondaEnvException: Conda Env Exception: Unable to determine environment`

https://ssbjenkins.stsci.edu/blue/organizations/jenkins/STScI%2Fjwql/detail/PR-402/3/pipeline

**Comment by obviousrebel** [comment]
I believe this is related to the latest commit to the jenkins shared utils library https://github.com/spacetelescope/jenkins_shared_ci_utils/commit/61fdd601b48119d4e18329dd3d2c290f69ef2850
CC @rendinam

**Comment by rendinam** [comment]
Build 402 has been restarted after rolling back the utils library to the previous version.

**Comment by Johannes-Sahlmann** [comment]
Thanks. the build has passed.
