### ISSUE TITLE
More informative errors for auth failure

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/jwql#408]
As @Johannes-Sahlmann discovered in #406, the errors that the web app throws if you don't have your `client` or `auth_mast` keywords in the `config.json` file defined properly are not very helpful.

We should add custom error messages there so it is easier for users to tell if something isn't working because of their configuration file.

(Related philosophical question: how do we balance informative error messages for developers with secrecy to maintain security?)

**Comment by Johannes-Sahlmann** [comment]
I think a place to put these checks is https://github.com/spacetelescope/jwql/blob/93de48a43debc9af705d96cddc91a0084dc0dda9/jwql/website/apps/jwql/oauth.py#L54
