### ISSUE TITLE
Import environment bokeh version in HTML

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/jwql#438]
As described in #425, having the environment Bokeh version NOT match the HTML template Bokeh version can cause problems.

I wrote some tests #429 that will test and make sure this is always the case in the future, but we could be even smarter about this if we programmatically set the Bokeh version using a Django variable. We could even include it in `context_processors` so it happens behind the scenes.

**Comment by bourque** [comment]
As i mentioned in #429, it might also help us to remove some of the potentially unnecessary calls to import `bokeh` in the various HTML templates; it would be a few less lines of code to have to worry about in situations like these.
