### ISSUE TITLE
Create django sitemap for web app

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#458]
We should build a sitemap for the web app, as suggested by the accessibility compliance guidelines (https://innerspace.stsci.edu/pages/viewpage.action?spaceKey=A5C&title=Webpage+Checklist).  It would also help with potential future web scrapers.

**Comment by bhilbert4** [comment]
With the JWQL web app not being a public tool, and used by a limited number of internal users, a site map does not seem necessary at the moment.
