### ISSUE TITLE
Use MAST Isilon directory as filesystem

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/jwql#468]
As @bourque and I remembered yesterday, the `jwqladm` user on the virtual machine has access to the MAST Isilon directory, which contains more data than the copy we've been using up until now from Mary Romelfanger. Using the MAST directory as our filesystem would give our web app/monitors access to more data.

This change might just be as simple as updating the `filesystem` key in each of our personal `config.json` files.

If we do this, though, we'll need to be sure to integrate the ASB permissions-checking feature to make sure that we're not doing anything illicit (i.e. making preview images that live in unrestricted directories) with proprietary data.

**Comment by bourque** [comment]
Whenever this is completed, we should reach out to Peter Forshay:

> Brian and I have been doing some more work on porting our archive query interface to a web service and we’re beginning to look into linking search results to jwql.  When we have that in place, live jwql data will be immediately useful for finding and viewing data during rehearsals.  We don’t have any live prototypes just yet, but we’ll keep you posted on our progress and if you could give us a shout when jwql gets live data, that’d be great!
