### ISSUE TITLE
Complete Application Security Assessment

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#502]
OWASP has a way to assess the security of an application, which has been detailed in [this innerspace page](https://innerspace.stsci.edu/display/JWQLPROJ/Copy+of+Application+Security+Assessment+Template+V4.0).  We should go through this as best we can and see where we can improve.

**Comment by bsunnquist** [comment]
Perhaps related, I am currently storing full central storage paths in the database tables for the bias/readnoise monitors - is this something I should change as part of this security sweep, or is the database protected?

**Comment by bourque** [comment]
@bsunnquist Yes, I would advise to not store the *full* path to the items, but storing the path reletative to the main directories listed in the config file should be fine.  For example, appending something like `bias_monitor/some_dir/some_file.txt` to what is returned by `utils.get_config()['outputs']` would hide the full path to the file in the `outputs` directory in central storage.

**Comment by bsunnquist** [comment]
@bourque sounds good - I can make a PR with those changes and link it here

**Comment by bourque** [comment]
This issue might actually not be needed to be resolved.  Since the production web app is going to be behind a SSO layer and only available to internal instrument team members, we need not worry so much.  I will close this for now, but if ITSD ends up requiring this we can re-open it.

**Comment by mfixstsci** [comment]
🤞 Let's hope so, this list is pretty long.
