### ISSUE TITLE
Document/diagram how end-to-end authentication (will) work

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#556]
There are a handful of systems involved in authenticating users and allowing certain access to certain data, such as:

- the web app admin account
- `auth.mast`  
- The MAST data cache
- software used to determine who has access to a specific dataset

It would be useful to document and/or diagram how this all works.

**Comment by Joe-Sin7h** [comment]
I would like to work on this issue . Please assign me to this issue @bourque

**Comment by bourque** [comment]
I have drafted a document that describes authentication here: [https://innerspace.stsci.edu/display/JWQLPROJ/Authentication+Overview](https://innerspace.stsci.edu/display/JWQLPROJ/Authentication+Overview).
