### ISSUE TITLE
Build Image Anomaly results page(s)

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#566]
A useful webpage on the web app to have is one that allows users to see all images that were flagged with specific anomalies, ideally filterable and sortable by metadata.

This may not be possible until #565 is complete.

**Comment by bourque** [comment]
This will also be important for display results of the Optical Short monitor (#564, @tnking97).

**Comment by tnking97** [comment]
The optical short monitor should be included in this webpage if the results are filterable/sortable by metadata including exposure time and specific anomalies.
