### ISSUE TITLE
Build Bad Pixel Monitor bokeh plots

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#588]

**Comment by bhilbert4** [comment]
My initial thought on this is to have a table, similar to what @mfixstsci showed at the meeting yesterday, showing just the entries for the latest run of the bad pixel monitor. And then have an image of the detector with colored dots showing the locations/flavors of newly found bad pixels.

**Comment by bourque** [comment]
This will be completed with the merge of #612
