### ISSUE TITLE
Create wiki page describing how to add/update dependencies

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#616]
Adding and/or updating dependencies is not exactly straightforward, since it involves potentially modifying four different files (`environment_3.6.yml`, `requirements.txt`, `rtd_requirements.txt`, `setup.py`).  It would be helpful to have a wiki page that describes when and how to modify these files, and what the purpose of each file is.

**Comment by Joe-Sin7h** [comment]
I would like to help on wiki page . Please assign me this issue @bourque

**Comment by bourque** [comment]
I am going to consider this done now that @tnking97 and @mfixstsci had a turn at using and editing the wiki page.
