### ISSUE TITLE
Update Bokeh to latest version

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#632]
I remember there was some reason that we were holding off on upgrading Bokeh from 1.3.4. However, Bokeh is now up to version 2.2.1 I believe. We should look into upgrading the version used for JWQL in order to take advantage of new features and so that we minimize the number of plots created under 1.3.4 which may need to be tweaked to work under the new version.

For example, one difference I ran into today was that the keyword "legend", which is used in 1.3.4 to denote the string printed in the legend for a particular element, has been changed to "legend_label" in version 2.2.1.

**Comment by bourque** [comment]
Good idea, let's try to get to this next sprint.
