### ISSUE TITLE
Improve Bad Pixel Monitor bokeh plots

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#640]
We will have an initial implementation of the Bad Pixel Monitor bokeh plots with the merge of #612, however we should make sure that the plots are showing the data/results that the instrument teams expect.

**Comment by bhilbert4** [comment]
The update I had wanted to make to the Bad Pixel Monitor page was implemented in #673. I don't have any other improvements on my list. Should we close this until a specific request for a change is made?

**Comment by bourque** [comment]
@bhilbert4, yes, that sounds good to me!
