### ISSUE TITLE
Speed up Readnoise Monitor webpage loading time

### ISSUE THREAD

**Issue by bsunnquist** [spacetelescope/jwql#681]
Rather than creating a separate ReadnoiseMonitor() class for each amp in `bokeh_containers.py`, create a separate plot for each amp in the corresponding yaml file that is updated once for each aperture (e.g. see Bias Monitor webpage code).

This strategy should decrease the page load time by ~2x.

**Comment by bourque** [comment]
@bsunnquist I'm doing some sprint planning and was just wondering if you would like/ be able to complete this for the `v0.26` sprint?

**Comment by bsunnquist** [comment]
@bourque sounds good!
