### ISSUE TITLE
Switch master branch to 'main'

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#685]
The latest version of `git` call the default branch `main` now instead of `master`, so we should change our branch name to reflect that.

**Comment by mfixstsci** [comment]
@bourque I can do this one, do I need special privileges to have access to to the settings tab of the repository to rename the default branch?

**Comment by bourque** [comment]
@mfixstsci Good question, I'm not really sure, but I've given you Admin access for the time being in order to do this!

**Comment by bourque** [comment]
@mfixstsci When you do this, could you also make sure that any references to `master` in our documentation are also switched over? I'm not sure there are any, but something to check.

**Comment by mfixstsci** [comment]
@bourque can do!

**Comment by bourque** [comment]
This is now completed.  Thanks @mfixstsci!

**Comment by mfixstsci** [comment]
Thanks @bourque should have closed the loop! Pushing directly to the `upstream` remote is weird.

**Comment by bourque** [comment]
Haha yeah, it feels wrong ...
