### ISSUE TITLE
Provide an easy way for users to report bugs/submit feature requests

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#689]
We should add some documentation somewhere (on our GitHub README, website, or both) that tells users how to open up a GitHub issue to report bugs and/or submit feature requests.  Perhaps we can also add a GitHub bot or issue template that also helps users.

**Comment by tnking97** [comment]
This documentation already exists on the [JWQL GitHub README](https://github.com/spacetelescope/jwql/blob/develop/README.md#issue-reporting--feature-requests) and the website [About](https://dljwql.stsci.edu/about/) page under the 'Contact' section.
