### ISSUE TITLE
Update branch name in fetch+installation job on VMs

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#710]
Now that the main branch of JWQL has been changed from `master` to `main`, the cron job that etches and installs JWQL onto the dev, test, and production linux servers needs to be updated to install the `main` branch. Currently it is still trying to install `master` and is failing.

**Comment by bourque** [comment]
Thanks for catching that @bhilbert4!  I've updated the `crontab`s, so hopefully this is fixed now!
