### ISSUE TITLE
Ensure newly-created database tables are readable by JWQL database accounts

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#714]
The JWQLDB database is managed by two accounts, one is read-only, one is read & write.  After using `reset_database.py`, it appears that newly-created tables are not readable by the read-only account, as performing a `SELECT` query on a given table results in a permissions error.

We should figure out if there is any way to grant read permissions to tables through our current `database_interface.py`/`reset_database.py` `sqlalchemy` solution.

**Comment by mfixstsci** [comment]
@bourque I can take this one, I don't have any `in progress` items for the `v1.0.0` project board.

**Comment by bourque** [comment]
Thanks @mfixstsci!
