### ISSUE TITLE
8 June 2021: Enable readthedocs test build with PRs 

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#739]
#724 passed all CI tests before being merged, but a check of readthedocs shows that the build there is now failing.

We should enable a test readthedocs build with each PR so that we can more easily catch documentation errors. I've been using this with Mirage for over a year now, and it's very helpful. Instructions for setting this up are here (looks much easier to set up then it was when I enabled it for Mirage): https://docs.readthedocs.io/en/stable/pull-requests.html

I don't see the "Admin" tab they mention, so I must not have the permissions to enable this.

**Comment by bhilbert4** [comment]
Log of the failing build: 
https://readthedocs.org/projects/jwql/builds/13958097/

**Comment by bourque** [comment]
Thanks @bhilbert4, this is a great idea!

**Comment by bourque** [comment]
This is now set up, however it appears that the builds get stuck on "pending" (e.g. https://github.com/spacetelescope/jwql/pull/726) even though when clicking on "Details", the build is successful on RTD.

**Comment by bourque** [comment]
Nevermind, the stuck RTD build appears to have fixed itself 🤷
