### ISSUE TITLE
config file missing on dev server

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#752]
The latest cron job emails indicate that config.json is not being found. Does the file need to be copied over from the old location into the main jwql directory on the development server?

**Comment by bourque** [comment]
This should fix itself when we point the dev server back to the latest `develop` branch.  Right now things are pointed to a branch used for #748 which is still expecting the `config.json` file to be in `jwql/` instead of `jwql/jwql/`

**Comment by bourque** [comment]
I believe this is now resolved.
