### ISSUE TITLE
Dashboard plots should have integer number for y-axis values

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#756]
There are various plots in the Dashboard view of the web app that use scientific notation for y-axis values (e.g. `8.000 e+5`).  These values would probably be easier to read/comprehend in pure integer form (e.g. `800000`).

**Comment by bourque** [comment]
@mfixstsci Here is another low-hanging fruit for the dashboard if you want it!

**Comment by mfixstsci** [comment]
Thanks @bourque I'll tie it in with #783.
