### ISSUE TITLE
Ask instrument teams for updated priorities for monitoring

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#769]
After our 1.0 release, we will be able to start developing new monitors for the application.  I think ~2018 was the last time we asked teams about which monitors they would like and what the priorities were.  We should ask the instrument teams about this and update our priorities if necessary.

**Comment by bourque** [comment]
@bhilbert4 Yes, that was my intention

**Comment by bsunnquist** [comment]
Looking at our instrument monitor overview page, I think the Pedestal Monitor is already taken care of in the Bias Monitor (it tracks the average 0th group levels over time in darks) - it's marked 'critical' for NIRCam/NIRISS, so we could change those to complete if we're updating that page as part of this task

**Comment by bhilbert4** [comment]
For NIRCam, a discussion on slack has come up with several monitors that folks think should be high priority. Roughly in order of highest to lowest priority:

Data trending
TA monitor (look at repeatability/uncertainty of small angle maneuvers)
PSF characterization (encircled energy, etc)
Photometric Stability Monitor
Sky/telescope Background Monitor

**Comment by bourque** [comment]
Just noting here that @cracraft has indicated that MIRI is most interested in a TA monitor and Sky/Background Monitor.

Now that we have updated priorities from each instrument team, I think we can close this issue.
