### ISSUE TITLE
EDB mnemonics plotting results does not handle certain data types

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#778]
Currently the EDB mnemonics plotting feature works on time-series data (for example, the `IMIR_HK_ICE_SEC_VOLT4` mnemonic), but does not gracefully handle other data types such as string values (for example, the `IFGS_CTD_GS` mnemonic).

We should either find a way to support other data types (e.g. return a table of values instead of a plot?), or put in an error message stating that the mnemonic is of an unsupported datatype.

**Comment by mfixstsci** [comment]
I will take this one!

**Comment by bourque** [comment]
@mfixstsci I'm just checking back in on this one.  IIRC, you implemented a warning to the user if data is not able to be returned?  If that is the case, I'm inclined to close this issue.

**Comment by bourque** [comment]
I tried out the EDB for a mnemonic that returns string data (`IFGS_CTD_GS`) and see there is a message: "QUERY RESULT RETURNED NO DATA FOR IFGS_CTD_GS ON DATES 2019-04-02 00:00:00.000 - 2019-04-02 00:01:00.000", so I think this issue can be closed.

**Comment by mfixstsci** [comment]
@bourque thanks for closing, sorry I didn't respond earlier 😓 I remember looking into the non-numeric mnemonic issue when I restructured the EBD interface. Do we have a list of mnemonics with non-numerical data? I don't mind taking a deeper dive on this if needed.
