### ISSUE TITLE
Add more information to the About page

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#779]
Currently the About page on the web app describes an overview of the project, the technologies used, an overview of the instrument monitoring, and a description of the development team.

There are number of things we could add to this page to more thoroughly describe the project and how users may interact with it.

Here is a running list of things to add (or point to existing documentation via a hyperlink):
- [x] Describe the process for submitting a bug report and/or feature request (See #788)
- [x] Describe the process for authentication
- [x] Describe the process for contributing software changes to the project
- [x] Describe which data the application serves and where it comes from
- [x] Describe which monitors we support and where the algorithms come from
- [x] Add a table of contents

**Comment by bhilbert4** [comment]
We'll have to draw a line somewhere that separates information to go on the About page versus information to go on Readthedocs, or else we risk ending up with a huge About page that makes it hard to find information.

**Comment by bourque** [comment]
We should take out the `Describe the process for submitting a bug report and/or feature request` item and make it part of the v1.0 release.
