### ISSUE TITLE
Readnoise Monitor crash in new data search

### ISSUE THREAD

**Issue by bsunnquist** [spacetelescope/jwql#784]
**Describe the bug**
Readnoise Monitor is crashing on FGS due to a missing end_date parameter in the mast_query_darks function.

From a recent log file (readnoise_monitor_2021-08-10-04-30.log):
08/10/2021` 04:30:13 AM INFO: Begin logging for readnoise_monitor
08/10/2021 04:30:13 AM INFO: 
Working on aperture FGS1_FULL_OSS in fgs
08/10/2021 04:30:13 AM INFO: 	No query history for FGS1_FULL_OSS. Beginning search date will be set to 57357.0.
08/10/2021 04:30:13 AM INFO: 	Query times: 57327.0 59436.354322145264
08/10/2021 04:30:13 AM CRITICAL: Traceback (most recent call last):
  File "/home/svc_jwqladm_dev/jwql/jwql/jwql/utils/logging_functions.py", line 284, in wrapped
    func(*args, **kwargs)
  File "/home/svc_jwqladm_dev/jwql/jwql/jwql/utils/logging_functions.py", line 249, in wrapped
    func(*args, **kwargs)
  File "/home/svc_jwqladm_dev/jwql/jwql/jwql/instrument_monitors/common_monitors/readnoise_monitor.py", line 556, in run
    new_entries = mast_query_darks(instrument, aperture, self.query_start, self.query_end)
TypeError: mast_query_darks() missing 1 required positional argument: 'end_date'

08/10/2021 04:30:13 AM CRITICAL: CRASHED

**To Reproduce**
Run the monitor.

**Expected behavior**
The end date should just be the time the monitor was run. This is the first time this issue has happened.

**Comment by bhilbert4** [comment]
Is this on the dev server? Right now it's running one of my branches with some dark monitor fixes in it. Within that branch, I had to add readpattern to the list of query parameters in the mast_query_darks() function, so I think this is just showing that the readnoise monitor is missing that readpattern parameter.

Assuming that this dark_monitor fix is kept, we might need to find a way to include a wildcard for the readpattern parameter, or omit it entirely, for the readnoise monitor, if you don't care about readpattern. For the darks, I found that NIRCam has a bunch of old NRC_DARK files that use patterns other than RAPID, so I had to find a way to filter those out and keep only the RAPIDs.

**Comment by bsunnquist** [comment]
Yeah that makes sense, it looks like it's running successfully now. Is that dark_monitor change going to be kept? If so, then yes I could just update it to query all available read patterns in the readnoise monitor, or just run it for RAPID if the other instrument teams are only wanting to monitor that read pattern too (I think for NIRCam we'll only be expecting RAPID darks into the future).

**Comment by bhilbert4** [comment]
Looking at the code the other day, I was surprised that it was failing. The way I updated the function, if a readpattern is not given, then that parameter is not added to the parameter dictionary that is passed to the MAST query. So the query for readnoise should be the same as it was previously, unless I missed something in my code. I'm not sure when @bourque switched away from the updated dark monitor branch, but I think it was only in the last day or two.
