### ISSUE TITLE
MAST Query Level 1b Products

### ISSUE THREAD

**Issue by tnking97** [spacetelescope/jwql#797]
Level 1b products may not be retrieved if Level 3 Products are available because the MAST astroquery request method might retrieve only the final products. It will be useful to do a check throughout the repository for MAST queries retrieving these products and ensure that the expected results are retrieved. Are there cases in which we would not want all of the level 1b products? @tnking97 has some (slightly lengthy) code that can address this.

**Comment by bhilbert4** [comment]
This seems to have been fixed on MAST's end. Uncal files appear in all search results now.
