### ISSUE TITLE
Header display inconsistencies

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#803]
While working on #664 I found what looks to be some inconsistencies/problems with the header display code. Currently, it looks like the header from the rate.fits file is displayed, regardless of the filetype chosen by the radio buttons.

In urls.py, the URL for the header display is given as:
/instrument/filename/header/

However, the change_filetype function in jwql.js specifies that:
fits_filename = file_root + '_' + type, where type is a suffix like rate, uncal, etc
It then sets the URL for viewing the header as:
'/' + inst + '/' + fits_filename + '/header/'
implying that the filename suffix is part of the URL.

The actual URL when looking at a header though is e.g. /FGS/jw86600008001_02101_00010_guider2/header/
so there is no suffix there (aka 'type' in the change_filetype function).

In view_image.html, when setting up the radio buttons for the different types of files, it is calling the change_filetype function and providing the suffix (e.g. rateints), so I would expect the resulting URL to be /FGS/jw86600008001_02101_00010_guider2_rateints/header/

**Comment by bourque** [comment]
Thanks for the nice description here @bhilbert4.  We will try to take care of this for the `v1.1` release.
