### ISSUE TITLE
Improve loading times throughout the web app

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#816]
There are various pages in the web app (particularly the instrument archive and specific proposal webpages) that take a long time to load, even on the dev/test/ops servers.  We should investigate the reason(s) behind this and try to make improvements.

**Comment by bhilbert4** [comment]
While investigating the instrument archive pages using the test server, I found it's taking about 90 seconds to query mast and get the results back. Nothing else up through creating the JsonResponse object takes more than 1 second. It still doesn't answer the question of why the webpage never loads, but it's something. 

Currently the get_filenames_by_instrument function queries MAST, and then filters the results based on the requested restriction of public or proprietary. But in archived_proposals_ajax , get_filenames_by_instrument is called once for public files and once for proprietary. So MAST is being queried twice. I think it might make more sense to pull the MAST query into its own function. Then call that once, save the result somewhere, and have get_filenames_by_instrument simply do the filtering, which takes only a hundredth of a second each time.

**Comment by bhilbert4** [comment]
Timing results of various functions in data_containers.py, working on the test server and pointing to the pre-flight test data filesystem:

Before get_expstart: 2021-12-30 19:39:45.345325
After get_expstart: 2021-12-30 19:39:45.457516
Elapsed time: 0.11219099999735249   ---------> This includes a MAST query. This could be a problem if called on lots of files

Before get_all_proposals: 2021-12-30 19:39:45.475330
After get_all_proposals: 2021-12-30 19:39:45.485729
Elapsed time: 0.010398999997107694

Before get_filenames_by_instrument: 2021-12-30 19:39:45.486449
After get_filenames_by_instrument: 2021-12-30 19:41:00.758608
Elapsed time: 75.27215899999788  ----------> This includes a MAST query

Before get_filenames_by_proposal: 2021-12-30 19:41:00.759614
After get_filenames_by_proposal: 2021-12-30 19:41:00.816628
Elapsed time: 0.05701399999793466

Before get_filenames_by_rootname: 2021-12-30 19:41:00.817512
After get_filenames_by_rootname: 2021-12-30 19:41:00.819713
Elapsed time: 0.0022010000094496718 ---> glob for files in a single directory

Before get_header_info: 2021-12-30 19:41:00.820454
After get_header_info: 2021-12-30 19:41:01.048803
Elapsed time: 0.22834899999679692 ----> Uses astropy fits. This could be a problem if called on lots of files.

Before get_image_info: 2021-12-30 19:41:01.050104
WARNING:root:SUBSTR and SUBSIZE header keywords not found
After get_image_info: 2021-12-30 19:41:14.064554
Elapsed time: 13.014450000004985  ----> 2 calls to glob. Perhaps this had to create a preview image for this particular test case. Not sure...

Before get_instrument_proposals: 2021-12-30 19:41:14.065973
After get_instrument_proposals: 2021-12-30 19:42:41.962256
Elapsed time: 87.89628299999492 ----> Uses a MAST query and some simple filtering

Before get_preview_images_by_instrument: 2021-12-30 19:42:41.964320
After get_preview_images_by_instrument: 2021-12-30 20:02:06.222492
Elapsed time: 1164.2581720000085  ------> MAST query, followed by call to glob for _**all preview images in the filesystem**_. Replacing the latter with a file/database entry that lists preview image filenames seems like low-hanging fruit for a speed improvement, especially if you assume the MAST query here is in line with those seen above, where they took ~80-100 seconds.

Before get_preview_images_by_proposal: 2021-12-30 20:02:06.225339
After get_preview_images_by_proposal: 2021-12-30 20:02:06.255655
Elapsed time: 0.030316000004759758

Before get_preview_images_by_rootname: 2021-12-30 20:02:06.256648
After get_preview_images_by_rootname: 2021-12-30 20:02:06.267215
Elapsed time: 0.010567000011008076

Before get_thumbnails_by_instrument: 2021-12-30 20:02:06.268180
After get_thumbnails_by_instrument: 2021-12-30 20:08:51.351778
Elapsed time: 405.08359799999704 ------> MAST query, followed by call to glob for _**all thumbnail images in the filesystem**_. Replacing the latter with a file/database entry that lists preview image filenames seems like low-hanging fruit for a speed improvement, especially if you assume the MAST query here is in line with those seen above, where they took ~80-100 seconds.

Before get_thumbnails_by_proposal: 2021-12-30 20:08:51.353782
After get_thumbnails_by_proposal: 2021-12-30 20:08:51.363807
Elapsed time: 0.010024999994939776

Before get_thumbnails_by_rootname: 2021-12-30 20:08:51.365036
After get_thumbnails_by_rootname: 2021-12-30 20:08:51.367886
Elapsed time: 0.002849999986409557

Before thumbnails_ajax: 2021-12-30 20:08:51.368585
After thumbnails_ajax: 2021-12-30 20:10:18.544290
Elapsed time: 87.17570499999994  ---> calls get_filenames_by_instrument (~75 sec above), plus get_expstart on each returned file.

thumbnails_query_ajax timing test is on hold for the moment. It's finding (and crashing) on *.pod and *.sqlite files in the filesystem. I've asked the pipeline developers if those files will actually be present in the real filesystem. If so we'll have to explicitly ignore them in get_filenames_by_rootname().

**Comment by bhilbert4** [comment]
Timing test results for only the MAST query itself, for each instrument, as done from the test server:

NIRCam
110.4522830000036 sec
50000 files

FGS
0.20069300000109536 sec
2215 files

NIRSpec
1.0008210000073348 sec
10128 files

MIRI
0.3112189999949777 sec
8244 files

NIRISS
0.6722399999954831 sec
40063 files

**Comment by bhilbert4** [comment]
Code used for the timing tests:
```
service = "Mast.Jwst.Filtered.NIRISS"
restriction = 'public'
parameters = {"columns": "filename, isRestricted",
               "filters": []}
                                                                                                                                    
start = Time.now()
response = Mast.service_request_async(service, parameters)
end = Time.now()
if restriction == 'all':
    filenames = [item['filename'] for item in result['data']]
elif restriction == 'public':
    filenames = [item['filename'] for item in result['data'] if item['isRestricted'] is False]
elif restriction == 'proprietary':
    filenames = [item['filename'] for item in result['data'] if item['isRestricted'] is True]
print((end-start).sec)
print(len(filenames))
```

**Comment by bourque** [comment]
I am just noting here that the 'query the archive' feature on the homepage is also very slow and we should look into improving the speed there too.

**Comment by bhilbert4** [comment]
@bourque any response from the archive folks about NIRCam being extra-slow? Or did they wait out the clock and now the rehearsal data is gone and we can't investigate any deeper?

**Comment by bhilbert4** [comment]
Digging into the query the archive feature on the homepage, I think the slowness here comes from 2 sources:
1) MAST is queried once for each requested instrument.
2) glob is called on the entire filesystem to look for thumbnail images. 

I'm not sure there's a way around 1), but 2) is another case where maintaining a file with a list of thumbnail filenames would probably help.

**Comment by york-stsci** [comment]
Just saw this going by, and had a thought on 2. When looking for thumbnails, do you already know the names of data files? Because if so, then can you just generate thumbnail name from data file name and check for existence?
