### ISSUE TITLE
Find a way to minimize downtime

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#819]
Sometimes the web server(s) go down for various reasons.  When this happens, we are not made aware of the downtime until someone goes to use the web app.  We should develop a way to alert the JWQL team of when the web servers go down (perhaps something like DataDog could help with this?).  It would be even better if we could automate a process that brings the servers back up automatically.

**Comment by york-stsci** [comment]
The jwql service has been set to automatically restart on the production server. This has not yet been tested. Hopefully we will be able to do testing soon.

**Comment by bhilbert4** [comment]
Testing results look good. The server was intentionally brought down, and then automatically restarted.
