### ISSUE TITLE
Images not displaying in Readnoise Monitor

### ISSUE THREAD

**Issue by bsunnquist** [spacetelescope/jwql#835]
The png images aren't displaying on the NIRCam Readnoise (and probably the Bias) Monitor pages. This might be due to me storing their dev directory filepaths in the database tables whereas the web app looks in the ops directory.

**Comment by bsunnquist** [comment]
i.e. see line ~133 in monitor_readnoise_bokeh.py
`diff_image_png = os.path.join('/static', '/'.join(diff_image_png.split('/')[-6:]))`

**Comment by bsunnquist** [comment]
Update - I don't think this is a problem with the image path in the database for these monitors. They are correctly set to the ops path (not dev) and they exist.

**Comment by bsunnquist** [comment]
The first flight data came in and these images are now displaying correctly! I'm not sure what changed, but just FYI @bourque I'm going to close this one.

**Comment by bourque** [comment]
Thanks @bsunnquist!
