### ISSUE TITLE
Extend support of EDB mnemonics plot feature to non-numeric data types

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#858]
Currently the EDB mnemonics plot feature on the EDB page of the web app only supports plotting `real` data types.  However, some mnemonics contain other data types such as `bigint`, `varchar`, etc.  We should either find a way to plot such results in a meaningful way, or warn the user that it is an unsupported datatype.

**Comment by bhilbert4** [comment]
I have made some major changes to the EDB plotting function as part of #832. So perhaps I should include these updates in there as well.

**Comment by bourque** [comment]
See #868
