### ISSUE TITLE
Build database table(s) for tracking filesystem monitor stats

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#86]
With the addition of the filesystem monitor (#69), it would be useful to store the statistics in a database table rather than static text files.  This would make it easier to assign labels to numbers, and open the possibility of storing/plotting more filetypes.

**Comment by SaOgaz** [comment]
Current blocker: trying to get our access to the DB working.  Right now I'm having problems even logging into the admin account.

**Comment by bourque** [comment]
@cracraft @SaOgaz How is it going on this?  Have you been able to connect and use the development database?  Is there anything I can do to help get what you have implemented?  It would be nice if we could get this in for our next release.

**Comment by SaOgaz** [comment]
I'm in a sprint this week and next, so won't have any time until then.  I'm starting to think that maybe this should be assigned to someone else.  I don't see myself having enough time in the near future.  😞

**Comment by bourque** [comment]
@SaOgaz @cracraft Thats fine!  If one of you could open a WIP PR with what you have so far, I could help out.

**Comment by SaOgaz** [comment]
Will try my best to do that by end of tomorrow.

**Comment by cracraft** [comment]
I know we have code ready to test, but I don't even know where to find the latest version.

**Comment by SaOgaz** [comment]
@cracraft I think I have it on my local machine. I will open a WIP PR.

**Comment by SaOgaz** [comment]
#328
