### ISSUE TITLE
Oversized NIRCam display images

### ISSUE THREAD

**Issue by bsunnquist** [spacetelescope/jwql#866]
Some NIRCam preview images are oversized and overlap the anomaly checklist, e.g.:
https://jwql-dev.stsci.edu/NIRCam/jw01057005001_02102_00001_nrca1/
https://jwql-dev.stsci.edu/NIRCam/jw01057006001_02102_00001_nrcb1/

Others are fine though, e.g.:
https://jwql-dev.stsci.edu/NIRCam/jw01057003001_03101_00024_nrcblong/

**Comment by bhilbert4** [comment]
The code is set up such that all preview images have a length of 8 inches in their longest dimension. So it seems like this must be an issue of how the images are displayed, rather than the actual images themselves?

**Comment by bhilbert4** [comment]
The tick labels on the colorbars are also strange. In the SUBSTRIPE256 case, there are two sets of labels.

**Comment by bhilbert4** [comment]
Sounds good. I also looked into the generate_preview_images code the other day and am pretty convinced that it's not explicitly making images that are too large in some cases but not others. I tried looking into the code that places the images in the html files to see if there was some issue with the display size, but I wasn't able to make sense of it enough to tell for sure.

**Comment by BradleySappington** [comment]
@bsunnquist - is this still an issue you are encountering?

**Comment by bsunnquist** [comment]
@BradleySappington Nope - it all looks good now! I'll go ahead and close this issue.
