### ISSUE TITLE
Proposal pages not showing thumbnails for NIRCam mosaics

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#869]
The proposal pages for NIRCam (e.g. https://jwql.stsci.edu/NIRCam/archive/01135/) are not rendering the thumbnails for mosaicked datasets.  I believe the issue is not in the creation of mosaicked thumbnails, but in the front end of the web app wherein the webapp expects filenames for individual thumbnails by detectors instead of a mosaicked image.

**Comment by bsunnquist** [comment]
Similar issue for NIRSpec here https://jwql.stsci.edu/NIRSpec/archive/01175/

**Comment by bourque** [comment]
This issue is now redundant with #897
