### ISSUE TITLE
Proposal page improvements

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#875]
Some potential improvements:

- [ ] Add exposure number to mouseover panel (if not enough room, remove exposure date)
- [x] Default sort by should be by observation date
- [ ] Proposal status/information should be placed before sorting options

Credit Jo Taylor for some of these suggestions!

**Comment by bhilbert4** [comment]
Current default sort is reverse chronological (newest first). 

Exposure number addition is covered in #1019

**Comment by bhilbert4** [comment]
Adding info to the mouseover is captured in #1019 
Moving the proposal status above the sorting options will not be done at this time.
