### ISSUE TITLE
Preview image page improvements

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#877]
Some potential improvements:

- [x]  Add observation date and exposure number to info at top of page.  Other possible options for info at the top (if enough space) are: filter, readout mode, exposure type, exposure time.
- [x]  Put units on colorbar (including if data is in log scale)
- [x] Integration number in slider is different than what is reported in the image title/filename
- [x]  Ensure the order of the "view file type" is the same for all images
- [ ]  The virtical colorbar is too squished for small subarray images (e.g. https://jwql.stsci.edu/NIRISS/jw01078002001_02103_00001_nis/)
- [ ]  Increase weight of font and ticks a little bit

Credit Jo Taylor for some of these suggestions!

**Comment by bhilbert4** [comment]
Most of this work has been done. Closing this issue. I've created a new issue, [JWQL-195](https://jira.stsci.edu/browse/JWQL-195), for the vertical colorbar issue.
