### ISSUE TITLE
Update feature description on EDB page

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#881]
Currently the EDB has a paragraph of text at the top of the page that describes what the feature is:

> This page allows interactive exploration of mnemonics stored in the Engineering Database (EDB) powered by MAST. Its use requires access privileges to the EDB (see [instructions page](https://outerspace.stsci.edu/pages/viewpage.action?spaceKey=JARI&title=JWST+Archive+Rehearsal+Instructions)). Functionality is built on top of the [astroquery.mast](https://astroquery.readthedocs.io/en/latest/mast/mast.html) module. Example programmatic code for EDB queries is available in this [Jupyter notebook](https://github.com/spacetelescope/jwql/tree/main/notebooks/edb_mnemonic_query.ipynb).

But some of this info is irrelevant or may be confusing.  This should be updated to:

> This page allows interactive exploration of mnemonics stored in the Engineering Database (EDB) powered by MAST.  Users may search for mnemonics and plot a particular mnemonic over a given time period. For more information about the EDB, see the [MAST documentation](https://outerspace.stsci.edu/display/MASTDOCS/Engineering+Data).

**Comment by bourque** [comment]
The relevant file to update is in `jwql/website/apps/jwql/templates/engineering_database.html`

**Comment by bhilbert4** [comment]
Resolved via #902
