### ISSUE TITLE
Check that database connections are being closed

### ISSUE THREAD

**Issue by bourque** [spacetelescope/jwql#891]
We recently had an issue come up in which the production database server was unable to support new connections because there were currently 100 open connections.  Perhaps there is something in our code that is not closing database connections after using features such as the `JWQLDB`

**Comment by mfixstsci** [comment]
I believe I found the culprit. In `jwql.website.apps.jwql.data_containers.build_table` is what I use to obtain the data but I don't tear the `session` object down afterwards.
