### ISSUE TITLE
Missing NIRCam preview images due to mosaics

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#897]
Currently, the web app shows many missing preview images for NIRCam data. This is because the preview image generator currently creates its own quick mosaics of preview images of NIRCam SW exposures. It creates these mosaic preview images, and skips the creation of preview images for individual detectors. However, in the web app pages for individual exposures, we have a separate page for each detector, and each of those pages is looking for a detector-specific preview image, rather than the mosaic.

We had originally thought that having these mosaic images would be a nice way to look at an entire exposure at once. However, with a separate page for each detector, combined with the fact that it will be hard to see small features/sources in a mosaic preview image, perhaps it makes more sense to go back to having detector-specific preview images for everything.

Maybe down the road we could add a link or a page that will show a full mosaic preview image if desired. But I'm thinking for the purposes of actual quick look, detector-specific might be better. 

@bourque @bsunnquist what do you think?

**Comment by bsunnquist** [comment]
Yeah that definitely makes sense to me

**Comment by bourque** [comment]
Yes, I agree as well!
