### ISSUE TITLE
Add Process ID to logs

### ISSUE THREAD

**Issue by BradleySappington** [spacetelescope/jwql#945]
Some cron jobs can last a long time, and identifying which cron job is challenging when they were kicked off around the same time

Adding a line in log file with the process_id will provide a reference so we can easily identify each process when running `top`

We ran into the issue that we had to stop some jobs that were being run daily, but taking more than a day to run (so multiple instances of the same job were running).  Needed an easier way to identify which jobs we needed to stop while preserving some other long running jobs that were kicked off at similar times.

**Comment by bhilbert4** [comment]
This is complete.
