### ISSUE TITLE
Bad thumbnail images

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#958]
Looks like we are still seeing some bad thumbnail images even after #949 . We need to investigate whether these are left over bad pixels from before the fix, or if there are still bad thumbnails being produced.

**Comment by bhilbert4** [comment]
NIRCam program 1602 still has 9 bad thumbnails. The preview images look ok though.

**Comment by BradleySappington** [comment]
@bhilbert4 What server is this on? What was the creation date for the thumbnails?

**Comment by bhilbert4** [comment]
This is the dev server. I'll log in and check the creation dates.

**Comment by bhilbert4** [comment]
Looks like May 7

**Comment by BradleySappington** [comment]
that was the same day that had the errors that I found in 01039
