### ISSUE TITLE
Investigate JS9 for interactive preview images

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/jwql#985]
JS9 could be an option for displaying an interactive preview image in the future. 
https://js9.si.edu/

Just like our idea to use a Bokeh server to speed up the interactive preview image as it is now, it looks like JS9 would also need a back end server in order to use it.

**Comment by bsunnquist** [comment]
I'm pretty sure this is what wfc3 quicklook used and it worked great - they might be able to help out if we go this route.

**Comment by bhilbert4** [comment]
As of July 2022, support for js9 has ended with the retirement of the developer. It sounds like no one is taking over support for it. https://github.com/ericmandel/js9/issues/88
