### ISSUE TITLE
Allow top-level filtering for MIRI MRS

### ISSUE THREAD

**Issue by drlaw1558** [spacetelescope/jwql#999]
It would be extremely useful to be able to select only programs that use the MIRI MRS as these program have unique issues compared to the MIRI imager.  At the top level 'Archived MIRI Images' page, it would therefore be useful to be able to downselect to show only programs that contain some MRS data instead of displaying all programs and having to click through each one to see which contain MRS vs imaging-only data.

**Comment by bhilbert4** [comment]
Thanks for bringing this up. I think it might be useful to set this up as even a more general filter for each instrument where the user can filter by EXP_TYPE.

For development, note that a given program can have multiple exp_type values, so we'd have to look at the exp_type values for all (uncal) files in a program, and then show that program if any of the files have a matching exp_type value.

It could also be useful to have this filter available on the program-specific pages if for example, someone wanted to look at only the TA images.
